## Numpy

Numpy arrays come in two flavors:
1. Vectors- 1D
2. Matrices-2D

In [1]:
#import Numpy
import numpy as np

In [2]:
#Create a numpy array
my_list=[1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#Create numpy arrays using inbuilt functions
# 1. arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#2. ones and zeros
np.zeros(2)

array([0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [9]:
# 3. Evenly spaced nos between a specified interval 
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
# 4. Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#Random
#rand, randn, randint and seed
np.random.rand(2)

array([0.02523219, 0.33851368])

In [12]:
np.random.randn(2)

array([-0.42962491,  0.25762995])

In [14]:
np.random.randint(1,100)

87

In [15]:
np.random.randint(1,100,10)

array([75, 53, 12, 61, 26, 14, 28, 56, 93, 75])

In [17]:
np.random.seed(42)
np.random.rand(2)

array([0.37454012, 0.95071431])

In [20]:
np.random.seed(42)
np.random.rand(2)

array([0.37454012, 0.95071431])

In [23]:
# Array attributes
# shape,reshape,dtype,max,min,argmax,argmin
arr=np.array([1,2,3,4])

In [24]:
arr

array([1, 2, 3, 4])

In [25]:
arr.shape

(4,)

In [26]:
arr.reshape(1,4)

array([[1, 2, 3, 4]])

In [37]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [29]:
arr.max()

4

In [30]:
arr.min()

1

In [31]:
arr.argmax()

3

In [32]:
arr.argmin()

0

In [34]:
arr.dtype

dtype('int32')